#spring
spring:
  datasource:
    url: jdbc:mysql://39.105.201.114:3306/quality?characterEncoding=utf8&useSSL=true
    username: root
    password: 7731ea5491bc
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  aop:
    auto: true
    ##开启CGLIB 作为动态代理类
    proxy-target-class: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#server
server:
  port: 8088
  servlet:
    session:
      timeout: 30M
#mybatis
mybatis-plus:
  type-aliases-package: com.quality.*.entity
  global-config:
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
  mapper-locations: classpath:/mapper/**/*Mapper.xml
#swagger
myswagger:
  packageName: com.quality
  serviceName: 质检认证服务
  description: 质检系统所有服务的接口
#log
logging:
  level:
    com:
      quality: debug
#fastfds是否使用缩略图
fs:
  useSm: true






